### ISSUE TITLE
Basic instructions?

### ISSUE THREAD

**Issue by jgberg** [igtm/storypoint-for-asana-chrome-ext#2]
I installed it, but it does nothing. We are on the asana free plan. Will it work with that? If it requires Asana fields then what fields should one make?
Basically there's zero information about how to use this thing, nor what really what it does in the three pictures you've provided... Does it add up the numbers? Does it deal with subtasks? etc etc.

**Comment by igtm** [comment]
Hi! Thank you for installing this app and Sorry for my late reply.

There are 2 types of projects in asana.
This app seemed not to work only on "List View" type project since something in Asana has changed on December 2018.
(Actually I only use "Board View", so I didn't notice that..)

and I fixed it just now!
so you can use this properly.

But, yes. I don't have enough documentation about this app.
I will write it someday.

> Does it add up the numbers? Does it deal with subtasks?

Yes to both questions :)

Thank you for informing me of the issue!
If you have any problem yet, feel free to reopen this issue.

**Comment by igtm** [comment]
I wrote some information on README just now!
https://github.com/igtm/storypoint-for-asana-chrome-ext/blob/master/README.md
